version: "3"
services:
  nginx:
    image: nginx
    container_name: nginx
    restart: always
    volumes:
      - ./root/frontend/dist/frontend:/usr/share/nginx/html
      - ./root/api/:/var/www/html
      - ./root/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 8085:80
    links:
      - fpm
  fpm:
    build:
      context: .
      dockerfile: ./api/api.dockerfile
    container_name: fpm
    ports:
      - 9000:9000
    volumes:
      - ./root/api/:/var/www/html
      - ./root/www.conf:/usr/local/etc/php-fpm.d/www.conf
    links:
      - mysql
    env_file: ./api/.env
  mysql:
    container_name: mysql
    image: mysql:5.7
    environment:
        - 'MYSQL_ROOT_PASSWORD=secret'
        - 'MYSQL_DATABASE=rgapp'
    ports:
      - 3306:3306